### ISSUE TITLE
pypgen install failure

### ISSUE THREAD

**Issue by justincbagley** [ngcrawford/pypgen#13]
Hi crawford,

I am having an issue that is keeping me from being able to install pypgen as described in the README. Here is the error message when I try "pip install pypgen" or do this with admin privileges:

````
Justin-Bagleys-MacBook-Pro-3:~ justinbagley$ pip install pypgen
Collecting pypgen
  Using cached pypgen-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qy/50knq60d42z3gwjxhx0gm8bc0000gn/T/pip-build-lcfzZq/pypgen/setup.py", line 1, in <module>
        import distribute_setup
    ImportError: No module named distribute_setup
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qy/50knq60d42z3gwjxhx0gm8bc0000gn/T/pip-build-lcfzZq/pypgen/
Justin-Bagleys-MacBook-Pro-3:~ justinbagley$ 

````

I also had trouble with using git for the download/install. Please help solve this issue. Many thanks.

Best,

Justin

**Comment by ngcrawford** [comment]
Hi Justin, I'm not currently maintaining pypgen.
